# backend/app/services/base/llm_adapter.py
# =================================================================
#
#                       LLM Adapter Base Class
#
# =================================================================
#
#  Purpose:
#  --------
#  Defines the abstract base class for all Large Language Model (LLM)
#  adapters. This ensures that any concrete LLM adapter implementation
#  (e.g., for OpenAI, HuggingFace, etc.) adheres to a consistent
#  interface for generating text responses.
#
#  Key Methods:
#  ------------
#  - generate_response: An asynchronous method that takes a text prompt
#    and returns a string response from the LLM.
#
# =================================================================

from abc import ABC, abstractmethod


class BaseLLMAdapter(ABC):
    """Abstract base class for LLM adapters."""

    @abstractmethod
    async def generate_response(self, prompt: str) -> str:
        """
        Generates a response from the LLM based on the given prompt.

        Args:
            prompt: The input text to send to the LLM.

        Returns:
            The text response generated by the LLM.
        """
        pass
